### ISSUE TITLE
Programmatically focus popover

### ISSUE THREAD

**Issue by dchapkine** [trueinteractions/tint2#139] opened 2015-06-20 13:42 UTC
I am trying to programmatically focus a popover that opens when i click on a tray icon.

Here is what doesn't work:
- `Control::focus` method on root popover object
- `Control::focus` on any child item of popover

Here is what works:
- `System.mouseDownAt` & `System.mouseUpAt` trick
- `System.clickAtControl`

So, simulating a click works to focus a control, however it's not acceptable solution for one simple reason: it programmatically moves mouse cursor, and does not restore previous mouse position.

Here is what could be a solution to this problem:
- fix `Control::focus` method (in case i understood correctly what it should do...)
- update `System.clickAtControl` method to restore previous mouse position after the click
- add `System.getMousePosition()` to give user a possibility to read/save/restore mouse coordinates

imho all three would be great additions to tint :) ,

Thanks !

---

Tested on: OSX 10.10.3 latest tint 2.1.15

**Comment by trevorlinton** [comment] 2015-06-21 19:23
@dchapkine Thanks again for reporting this, I ran a quick test with a pop over and wasnt able to replicate any issues.  Maybe i'm not understanding the issue.

Focus doesn't necessarily imply that the window will become the top or focused window.  I think what you'd be looking for is Window.bringToFront(), which causes the window to become the key window. Unfortunately on popovers there is no way to make it the top level window as its not designed to be a window but an anxillary information panel attached to another control. 

In addition, if the application is not the top level application bringing the window to the front will only mean the window will be the first responder to text/key input when the user has selected hte application.  There are ways of programmatically making the application the front application but its strongly discouraged by apple and generally a bad practice to force an application to the front. Usually its a better practice to use  application.attention or Notification to alert the user to an issue that needs to be resolved.

Perhaps if you have a use case you can provide me I can help figure out if this needs a feature enhancement, if its a defect or if its a design issue.

**Comment by dchapkine** [comment] 2015-06-21 20:59
@trevorlinton  thank you for looking into this issue,

>  I ran a quick test with a pop over and wasnt able to replicate any issues

Yes, i didn't include a code snippet to reproduce, my fault.

I will try to explain the issue. Consider this example:

popover.html
```
<!doctype html>
<head>
	<style type="text/css">

	#test
	{
		background: green;
		width: 80px;
		height: 80px;
	}

	#test:hover
	{
		background: red;
	}

	</style>
</head>
<body>
	<div id="test" onclick='document.getElementById("out").innerHTML += "</br> clicked" '></div>
	<div id="out"></div>
</body>
```

popover.js
```
require('Common');

application.exitAfterWindowsClose = false;

var isPopoverOpened = false;

var popOver = new PopOver();

var webview = new WebView();
webview.left = webview.right = webview.top = webview.bottom = 0;
popOver.appendChild(webview);
var imageWell = new ImageWell();
imageWell.image = "./tint.png"
imageWell.width = 22;
imageWell.height = 22;

imageWell.on('mousedown', function(e) {

	var bounds = imageWell.boundsOnScreen;

	if (!isPopoverOpened)
	{
		popOver.open(imageWell, 'bottom');

		// attempt to focus
		/*
		setTimeout(function() {
			
			//System.mouseDownAt(bounds.x  + bounds.width / 2, bounds.y + 50);
			//System.mouseUpAt(bounds.x  + bounds.width / 2, bounds.y + 50);
			//System.mouseUpAt(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
			
		}, 500);
		*/
	}
	else
	{
		popOver.close()
	}

	isPopoverOpened = !isPopoverOpened;
});

var statusBar = new StatusBar();
statusBar.custom = imageWell;

webview.location = "app://popover.html"; 
```

Here are the steps to reproduce the issue:
- run `tint popover.js`, by default it will focus our application, so we need to focus something else
- click on desktop to focus finder for example, finder menu will show on OSX status bar
- then click on systray icon of our tint app
- our popover opens, but if you check the OSX menu in status bar, finder still has focus
- since our app doesn't have focus, if you hover `#test` div, it won't receive the hover event
- for the same reason, if you click one time on  `#test` div, it won't receive the click event because our app wasn't focused in first place
- however, if you click second time or try to hover elements after first click, the webview will receive all the events because first click focused our app
- what i actualy want is to focus the popover when i click the systray icon, like this i will receive all mousemove and click events, without needing to focus the popover first.

The only solution i found to solve this issue programmatically is to use a `System.mouseDownAt` & `System.mouseUpAt` trick inside `imageWell.on('mousedown', function(e) {` event handler like this:

```
		// attempt to focus
		
		setTimeout(function() {
			
			System.mouseDownAt(bounds.x  + bounds.width / 2, bounds.y + 50);
			System.mouseUpAt(bounds.x  + bounds.width / 2, bounds.y + 50);
			System.mouseUpAt(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
			
		}, 500);
		
```

This basically waits 500ms for the popover to fully show up, then clicks on the top arrow of the popover to focus it, then moves the mouse cursor to the nearest position to the systray icon... since i don't have a method to read mouse coordinates before the click, this is the best i can do to minimize the "cursor jump effect"

After this dirty hack, focus works as expected:

![screen shot 2015-06-21 at 22 55 07](https://cloud.githubusercontent.com/assets/289632/8273320/acfea6b4-1868-11e5-808d-a0c1f71571d1.png)


> Usually its a better practice to use application.attention or Notification to alert the user to an issue that needs to be resolved

I agree with that, however In my case i don't use the popover for notifications, but as my main UI container, so notifications do not fit my needs there.


i also should mention that this issue applies to Window object too, except that even with a focus, it doesn't take mousemove events at all as discussed in this issue: #137 (which is the reason why i ended up using PopOver object instead of frameless Window). Click events on Window actualy fire as expected even if the window wasn't focused previously. I also tryied `Window.bringToFront()` method to focus the window, and it had no focus effect.

I hope this explains the issue a bit better.

**Comment by trevorlinton** [comment] 2015-06-22 23:57
@dchapkine Ah, I see what you mean. 

The issue is more or less exaggerated by the web view not capturing the mouse enter/mouse exit and hover events since its not the focused app. 

You can use the native call on OSX only to force the application to the foreground, however its not recommended to do this indescriminitely, perhaps limit its use only to click/mousedown events on the image well and you should be fine:

```javascript
application.native('activateIgnoringOtherApps', true);
```

It's part of the NSApplication class: https://developer.apple.com/library/mac//documentation/Cocoa/Reference/ApplicationKit/Classes/NSApplication_Class/index.html#//apple_ref/occ/instm/NSApplication/activateIgnoringOtherApps:

Let me know if this helps fix your issues.  I'll continue to look into how to get WebKit to not ignore mouse hover/mouse-enter/mouse-exit events on non-framed windows.  Once thats fixed it should make this work around unnecessary.

Let me know if you continue to have issues, feel free to close this out if you feel its been resolved, the other issue you filed on Webviews not hearing exit/enter events will be the main tracking point for the same issue were experiencing here.

**Comment by trevorlinton** [comment] 2015-06-26 02:29
@dchapkine Unfortunately the fix for NSWindow #137 did not fix this.  After consulting a lot of docs it seems theres no way to actually get the NSPopover to obey implicit mouse events without programming the entire thing yourself.  

However, my hope is the workaround of forcing the application to the foreground may help.  NSPopover's  are normally meant to be tied to a NSView on a NSWindow thus routing events for them, using them on a StatusBar isn't necessarily supported as the status bar has no concept of "key" or "main window", thus the appropriate events will never be routed.

Unfortunately there doesn't seem to be a very good fix for this.  Does forcing the application to the top on click help fix the issue? It's a bit of a hack, but if it works..

**Comment by dchapkine** [comment] 2015-06-27 14:15
@trevorlinton 

>NSPopover's are normally meant to be tied to a NSView on a NSWindow thus routing events for them, using them on a StatusBar isn't necessarily supported as the status bar has no concept of "key" or "main window", thus the appropriate events will never be routed.

Ok i understand.
Unless i am doing something wrong, it looks like `application.native('activateIgnoringOtherApps', true);` in combination with `Window.bringToFront()` doesn't focus the app

>Does forcing the application to the top on click help fix the issue? It's a bit of a hack, but if it works..

Yes, it's definitely dirty but simulating the click works, the only thing i would love to be able to do is to have a `System.getMousePosition() ` method so i can save then restore the exact mouse position after simulated click on the popover/window, so the user doesn't notice that the cursor jumped

>the fix for NSWindow #137

Thanks for fixing #137 , can't wait to try it :)

**Comment by trevorlinton** [comment] 2015-06-27 20:18
@dchapkine 

Here's the code I used:

```javascript
require('Common');

application.exitAfterWindowsClose = false;

var isPopoverOpened = false;

var popOver = new PopOver();

var webview = new WebView();
webview.left = webview.right = webview.top = webview.bottom = 0;
popOver.appendChild(webview);
var imageWell = new ImageWell();
imageWell.image = "./tools/compiler/test/tintruntime.png"
imageWell.width = 22;
imageWell.height = 22;

imageWell.on('mousedown', function(e) {
    application.native('activateIgnoringOtherApps', true); 
    var bounds = imageWell.boundsOnScreen;

    if (!isPopoverOpened)
    {
        popOver.open(imageWell, 'bottom');

        // attempt to focus
        /*
        setTimeout(function() {

            //System.mouseDownAt(bounds.x  + bounds.width / 2, bounds.y + 50);
            //System.mouseUpAt(bounds.x  + bounds.width / 2, bounds.y + 50);
            //System.mouseUpAt(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);

        }, 500);
        */
    }
    else
    {
        popOver.close()
    }

    isPopoverOpened = !isPopoverOpened;
});

var statusBar = new StatusBar();
statusBar.custom = imageWell;

webview.location = "app://popover.html"; 
```

Notice I just added the activation when the click happens.  Note this fixes the focus issue for a situation where another app is active and the user clicks the status icon, however if they then go focus another window after they click the status icon (with the popover left open), the hover events dont work until they re-click on the popover or statusicon.  However clicking on the statusbar will always give the app focus.

Is this what you were trying to achieve or am I miss-understanding the issue?.

Also, if you find yourself getting to a point where you could potentially share what you're building (not the source code, just screenshots and descriptions) we want to do a spotlight of different apps being built with Tint on our new homepage were designing, i'd love to include you in the spot light.

**Comment by dchapkine** [comment] 2015-06-28 22:33
@trevorlinton awesome, this code worked to focus popover. I misplaced it in my first tests -.- ...

BTW `application.native('activateIgnoringOtherApps', true) ` works for frameless Window too, and since #137 will be solved in 2.1.17, frameless Window should be now perfect on OSX.

> Also, if you find yourself getting to a point where you could potentially share what you're building (not the source code, just screenshots and descriptions) we want to do a spotlight of different apps being built with Tint on our new homepage were designing, i'd love to include you in the spot light

Sure, when i have the final thing ready, i will send a link. Is there a repository somewhere for new homepage ?

Thank you !

**Comment by trevorlinton** [comment] 2015-06-29 04:31
@dchapkine Were working right now to get it up (in additional to finally replace the Tint 1 Commercial version with Tint 2's commercial version), you can see a preview of the mocks at http://tint-website.herokuapp.com

I'll go ahead and close this out, if you find yourself needing additional features surrounding this (or we haven't fully addressed all of the items on here) feel free to reopen.

Thanks,
Trevor

**Closed by trevorlinton** 2015-06-29 04:31 UTC

**Comment by trevorlinton** [comment] 2015-06-29 04:57
@dchapkine Also, we added System.mousePosition property to get the x/y coordinates for the mouse cursor.  This will be in 2.1.17 out tomorrow.

**Comment by trevorlinton** [comment] 2015-07-26 05:18
This has been fixed, it however requires a slightly different approach, the example above (with all of the focus events) works in OSX and Windows:

```javascript
require('Common');

application.exitAfterWindowsClose = false;

var isPopoverOpened = false;
var popOver = new PopOver();
var webview = new WebView();
webview.left = webview.right = webview.top = webview.bottom = 0;
popOver.appendChild(webview);

var statusBar = new StatusBar();
statusBar.image = "./tools/tint.png"
statusBar.on('click', function() {
  // application.native('activateIgnoringOtherApps', true);
  popOver.open(statusBar, 'bottom');
});
```

If you have any other concerns or questions feel free to re-open this.
